# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.10"

gem "terminal-table", "~> 2.0"

gem "artii", "~> 2.1"
